name: "CICD for Nginx webapp using Dockerfile"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  nginx-image-build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME}}
          password: ${{ secrets.DOCKERHUBTOKEN}}
      
      - name: Setup Docker Buildx
        uses: docker/setup-builx-action@v2
      
      - name: Build Image and push to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUBUSERNAME}}/nginx-ubuntu:latest



          